default: &default
  sv_base_url: https://komin.malmo.se/
  site_search_url: //kominsok.malmo.se/
  site_search_ac_url: //kominsok.malmo.se/search/autocomplete
  asset_host: //assets.malmo.se/internal/v4/
  ua_account: 'UA-1659147-1'
  dashboard_base_url: "https://minsida.malmo.se/"

development: &development
  <<: *default
  sv_base_url: http://www.local.malmo.se:3031/
  asset_host: http://www.local.malmo.se:3039/assets/
  ua_account: 'UA-19475064-1'
  dashboard_base_url: "http://www.local.malmo.se:3031/"

staging:
  <<: *default
  sv_base_url: https://komin.test.malmo.se/
  asset_host: //assets.malmo.se/internal/v4-staging/
  ua_account: 'UA-19475064-1'
  dashboard_base_url: "https://minsidatest.malmo.se/"

production:
  <<: *default
  site_search_url: //kominsok.malmo.se/
  site_search_ac_url: //kominsok.malmo.se/search/autocomplete
